-   id: editorconfig-checker
    name: editorconfig-checker
    entry: editorconfig-checker
    language: python
    'types': [python]
    args: []
    require_serial: false
    additional_dependencies: []
